name: iplayer
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: any
  permission_handler: any
  hive_flutter: any
  hive: any
  path_provider: any
  pip_view: any
  media_store_plus: any
  dio: any
  shimmer: any
  shared_preferences: any
  flutter_downloader: any
  google_sign_in: any
  blur: any
  video_player: any
  chewie: any
  image_picker: any
  introduction_screen: any
  showcaseview: any

  animated_text_kit: any
  intro_slider: any
  smooth_page_indicator: any
  tutorial_coach_mark: any
  path: any
  floating_navbar: any
  animate_do: any
  flutter_overboard: any
  google_fonts: any
  intl: any
  fluttertoast: any
  screen_brightness: any
  volume_controller: ^2.0.4
  url_launcher: any
  flutter_animate: any
  curved_navigation_bar: any
  photo_manager: any
  lottie: any
  another_flushbar: any
  connectivity_plus: any
  provider: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  cupertino_icons: any


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: any


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - onboarding_image/on1.png
    - onboarding_image/on2.png
    - onboarding_image/on3.png
    - Anim/login.json
    - Anim/splash.json
    - Anim/onlottite1.json
    - Anim/onlottite2.json
    - Anim/onlottie3.json
    - Anim/onlottie3rd.json
    - Anim/login2.json
    - Anim/bird.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

